//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front.Business.Payments.List {
    
    
    public partial class PaymentsList {
        
        /// <summary>
        /// AccountingWizardMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Accounting.AccountingWizardMessageControl AccountingWizardMessage;
        
        /// <summary>
        /// SecondaryMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.Application.Menus.SecondaryMenu SecondaryMenu;
        
        /// <summary>
        /// AllMenuItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.Application.Menus.SecondaryMenuItem AllMenuItem;
        
        /// <summary>
        /// IncomingMenuItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.Application.Menus.SecondaryMenuItem IncomingMenuItem;
        
        /// <summary>
        /// OutgoingMenuItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.Application.Menus.SecondaryMenuItem OutgoingMenuItem;
        
        /// <summary>
        /// SearchInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.Application.Searching.SearchInputControl SearchInput;
        
        /// <summary>
        /// ImportMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Business.Payments.ImportPaymentMessage ImportMessage;
        
        /// <summary>
        /// PaymentsActionsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.Panel PaymentsActionsPanel;
        
        /// <summary>
        /// PrintCashBookLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.Pseudolink PrintCashBookLink;
        
        /// <summary>
        /// DownloadExcelPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Business.Excel.DownloadExcelPanel DownloadExcelPanel;
        
        /// <summary>
        /// ImportSuggestionPopup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Dialogs.Nanobox ImportSuggestionPopup;
        
        /// <summary>
        /// CloseLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.StaticText CloseLink;
        
        /// <summary>
        /// UsnWithPatentWarningMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Requisites.UsnWithPatentWarningMessage UsnWithPatentWarningMessage;
        
        /// <summary>
        /// Filter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Business.Payments.PaymentsFilter Filter;
        
        /// <summary>
        /// ExpandPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.Panel ExpandPanel;
        
        /// <summary>
        /// ExpandLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.StaticText ExpandLink;
        
        /// <summary>
        /// EmptyFilterResult control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.Panel EmptyFilterResult;
        
        /// <summary>
        /// NotEmptyListPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.Panel NotEmptyListPanel;
        
        /// <summary>
        /// FooterPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.Panel FooterPanel;
        
        /// <summary>
        /// NoSourceItemsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.System.Static.Panel NoSourceItemsPanel;
        
        /// <summary>
        /// VideoPlayer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Front.Controls.Application.Videos.VideoPlayer VideoPlayer;
    }
}
